import { PlusIcon, ListIcon, UserIcon, UsersIcon, CalendarIcon, FileTextIcon, BookOpenIcon, DollarSignIcon, MailIcon, ClipboardIcon, TruckIcon, SettingsIcon, TrashIcon, CheckIcon, DatabaseIcon, BriefcaseIcon, PrinterIcon, PencilIcon, LockOpenIcon, ClipboardListIcon, ClipboardCheckIcon, CakeIcon, AlignCenterHorizontalIcon, HeartIcon, LineChartIcon, NewspaperIcon , BarChartIcon , SchoolIcon} from '../utils/utils'

export const quickaction = [
    { color: 'addColorCode', title: 'Admit Student', icon: <UsersIcon className="h-6 w-6" /> , link:'/students/create' },
    { color: 'listingColorCode', title: 'Students Listing', icon: <ListIcon className="h-6 w-6" />, link: '/students/listing' },
    
    { colorCode: '#F59E0B', title: 'Add Teachers', icon: <UsersIcon className="h-6 w-6" /> , link: '/teacher/create'},
    { color: 'listingColorCode', title: 'List Teachers', icon: <ListIcon className="h-6 w-6" /> , link: '/teacher/listing' },

    { colorCode: '#4338CA', title: 'Enroll Student', icon: <UserIcon className="h-6 w-6" /> },
    { colorCode: '#10B981', title: 'View Attendance', icon: <CalendarIcon className="h-6 w-6" /> },
    // { colorCode: '#6B7280', title: 'Manage Courses', icon: <BookOpenIcon className="h-6 w-6" /> },
    { colorCode: '#3B82F6', title: 'Fees Management', icon: <DollarSignIcon className="h-6 w-6" /> },
    { colorCode: '#9333EA', title: 'Send Notifications', icon: <MailIcon className="h-6 w-6" /> },
    { colorCode: '#D97706', title: 'Manage Exams', icon: <ClipboardIcon className="h-6 w-6" /> },
    { colorCode: '#059669', title: 'Transport Management', icon: <TruckIcon className="h-6 w-6" /> },
    { colorCode: '#7C3AED', title: 'Settings', icon: <SettingsIcon className="h-6 w-6" /> },
    { colorCode: '#F43F5E', title: 'Delete Records', icon: <TrashIcon className="h-6 w-6" /> },
    { colorCode: '#22C55E', title: 'Approve Requests', icon: <CheckIcon className="h-6 w-6" /> },
    { colorCode: '#0369A1', title: 'Backup Data', icon: <DatabaseIcon className="h-6 w-6" /> },
    { colorCode: '#A855F7', title: 'Manage Staff', icon: <BriefcaseIcon className="h-6 w-6" /> },
    { colorCode: '#F97316', title: 'Print Documents', icon: <PrinterIcon className="h-6 w-6" /> },
    // { colorCode: '#0EA5E9', title: 'Edit Records', icon: <PencilIcon className="h-6 w-6" /> },
    { colorCode: '#EF4444', title: 'Manage Permissions', icon: <LockOpenIcon className="h-6 w-6" /> },
    { colorCode: '#6EE7B7', title: 'View Schedules', icon: <ClipboardListIcon className="h-6 w-6" /> },
    { colorCode: '#FB923C', title: 'Manage Assignments', icon: <ClipboardCheckIcon className="h-6 w-6" /> },
    { colorCode: '#8B5CF6', title: 'Student Events', icon: <CakeIcon className="h-6 w-6" /> },
    { colorCode: '#14B8A6', title: 'Manage Certificates', icon: <ClipboardIcon className="h-6 w-6" /> },
    // { colorCode: '#4B5563', title: 'Customize Settings', icon: <AlignCenterHorizontalIcon className="h-6 w-6" /> },
    { colorCode: '#7C3AED', title: 'Student Welfare', icon: <HeartIcon className="h-6 w-6" /> },
    // { colorCode: '#2563EB', title: 'Analytics Dashboard', icon: <LineChartIcon className="h-6 w-6" /> },
    { colorCode: '#F97316', title: 'Manage Transportation', icon: <TruckIcon className="h-6 w-6" /> },
    { colorCode: '#9333EA', title: 'Publish Announcements', icon: <NewspaperIcon className="h-6 w-6" /> },
    { colorCode: '#059669', title: 'Verify Documents', icon: <ClipboardCheckIcon className="h-6 w-6" /> },
    { colorCode: '#D97706', title: 'Manage Attendance', icon: <ClipboardCheckIcon className="h-6 w-6" /> },
    { colorCode: '#7C3AED', title: 'Generate Reports', icon: <BarChartIcon className="h-6 w-6" /> },
    { colorCode: '#F43F5E', title: 'Manage Transcripts', icon: <ClipboardIcon className="h-6 w-6" /> },
    { colorCode: '#22C55E', title: 'Approve Applications', icon: <ClipboardCheckIcon className="h-6 w-6" /> },
    // { colorCode: '#0369A1', title: 'Manage Enrollment', icon: <ClipboardIcon className="h-6 w-6" /> },
    { colorCode: '#A855F7', title: 'Manage Admissions', icon: <ClipboardIcon className="h-6 w-6" /> },
    { colorCode: '#F97316', title: 'Manage Registrations', icon: <ClipboardIcon className="h-6 w-6" /> },
    { colorCode: '#0EA5E9', title: 'Manage Classes', icon: <ClipboardIcon className="h-6 w-6" /> },
    // { colorCode: '#EF4444', title: 'Manage Disciplinary', icon: <ClipboardIcon className="h-6 w-6" /> },
    // { colorCode: '#6EE7B7', title: 'Manage Scholarships', icon: <ClipboardIcon className="h-6 w-6" /> },

]